# Generated by Django 4.2 on 2023-04-07 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activityId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivities',
            fields=[
                ('useractivityId', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Focal_app.activities')),
                ('username', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='Focal_app.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Focal_app.categories'),
        ),
    ]
